spring.application.name=VibeStream
spring.jwt.secret.key=__F]"HZ03j{bTK)FUlLb4Q+9^K4[+YH0
logging.level.org.springframework.security.web.FilterChainProxy=DEBUG
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration